apiVersion: 1

datasources:
  - name: DMARC Elasticsearch
    uid: dmarc-elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    isDefault: true
    editable: true
    jsonData:
      index: dmarc_aggregate-*
      interval: Monthly
      timeField: date_begin
      esVersion: 8
